# NumPy 실습 문제

아래 문제에 대해 풀이하시오.
(numpy 모듈 import 필요)


다음 리스트 `[1, 2, 3, 4, 5]`를 ndarray로 변환하고, 배열의 차원(ndim)과 형태(shape)을 출력하시오.

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)

1
(5,)



`np.arange()`를 이용해 0부터 20까지의 짝수로 이루어진 배열을 생성하시오.

In [4]:
even_arr = np.arange(0,21,2)
print(even_arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


다음 배열을 주어진 형태로 변환하시오.

In [6]:
arr = np.arange(12)

# (3, 4)
arr = np.arange(12).reshape(3, 4)
print(arr)

# (2, 3, 2)
arr2 = np.arange(12).reshape(2,3,2)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]



다음 제시된 배열에서, **3 이상인 값만 추출**하는 불리언 인덱싱 코드를 작성하시오.

In [8]:
arr = np.array([1, 3, 5, 2, 8, 3])
result = arr[arr>=3]
print(result)


[3 5 8 3]



다음 제시된 2차원 배열에서 **두 번째 행**만 슬라이싱하여 출력하시오.

In [9]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result = arr[1,]
print(result)

[40 50 60]


아래 리스트 기반 반복문을 벡터화 연산으로 개선하시오.

In [ ]:
data = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])
# arr = np.array(data)
# 리스트 기반 처리
result = []
for x in data:
    result.append(x * 3 + 1)

# 벡터화 연산 처리
result = arr * 3 + 1
print(result)

[ 4  7 10 13 16]



다음 제시된 배열에서 **모든 홀수에 10을 더하는 벡터화 연산**을 수행하시오.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
odd_arr = arr[:6:2]
result1 = odd_arr + 10
print(result1)

# arr_odd = (arr[arr % 2 != 0])

#-----------------------------------------------------------------

# 모든 데이터에서 홀수에만 +10 더하기
# arr_odd = np.where(arr % 2 != 0, arr + 10, arr))


[11 13 15]



다음 제시된 2차원 배열에서 **50보다 큰 값들만 추출하여** 새로운 배열로 만드시오.

In [20]:
arr = np.array([[12, 55, 72], [3, 88, 41], [60, 10, 99]])
arr50 = arr[arr > 50]
print(arr50)


[55 72 88 60 99]



브로드캐스팅을 이용하여 아래 배열에 값 5를 더하시오.

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 5
result = arr + scalar
print(result)

[[ 6  7  8]
 [ 9 10 11]]



3차원 배열을 생성하여 shape, ndim, size를 출력하는 코드를 작성하시오.

In [24]:
full_arr = np.full((3,3,3), 3)
print(full_arr.shape)
print(full_arr.ndim)
print(full_arr.size)


(3, 3, 3)
3
27


다음 배열에서 값을 최소 10, 최대 20으로 제한하시오.

In [25]:
arr = np.array([3, 12, 25, 18, 7, 22])
arr_clip = np.clip(arr, 10, 20)
print(arr_clip)

[10 12 20 18 10 20]


아래 데이터를 이용하여 학생별 총점을 구하시오.
단, reshape 및 브로드캐스팅을 활용할 것.

In [ ]:
# 3명의 학생 시험 점수 데이터 (응시 시험 수 : 4)
scores = np.array([
    80, 70, 90, 60,
    88, 75, 66, 95,
    55, 65, 70, 60
])

# scores를 (3,4) 형태로 재배열
arr = scores.reshape(3,4)
print(arr)
# 각 시험의 가중치 정보를 참고하여 총점 계산
weights = np.array([0.2, 0.3, 0.3, 0.2])
# 총점= 시험A*r시험A의가중치​ + 시험B*r시험B의가중치 + 시험C*r시험C의가중치 + 시험D*r시험D의가중치
result = arr.sum(axis=0) * weights
print(result)

# totals = arr * weights
# 시험 기준이 아니라 학생 기준이기 때문에 axis = 1 로 해서 계산

[[80 70 90 60]
 [88 75 66 95]
 [55 65 70 60]]
[44.6 63.  67.8 43. ]
